spring:
  application:
    name: test
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtualHost: /
server:
  port: 9999
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://admin:admin@node1:8100/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh
data:
 message: test3